-- Error Message
delete from dbo.ErrorMessages 
go
Insert dbo.ErrorMessages (ErrorMessageID, ErrorDescription, Severity, CreatedBy, CreatedDate, LastModifiedBy, LastModifiedDate)
values (50301, '%1 should not be null. We are unable to complete your request.', 16, 'Setup Script', getdate(), 'Setup Script', getdate())
Insert dbo.ErrorMessages (ErrorMessageID, ErrorDescription, Severity, CreatedBy, CreatedDate, LastModifiedBy, LastModifiedDate)
values (50302, '%1 not found. We are unable to complete your request.', 16, 'Setup Script', getdate(), 'Setup Script', getdate())
Insert dbo.ErrorMessages (ErrorMessageID, ErrorDescription, Severity, CreatedBy, CreatedDate, LastModifiedBy, LastModifiedDate)
values (50303, '%1: Cannot update row %2 for unknown reason.', 16, 'Setup Script', getdate(), 'Setup Script', getdate())
Insert dbo.ErrorMessages (ErrorMessageID, ErrorDescription, Severity, CreatedBy, CreatedDate, LastModifiedBy, LastModifiedDate)
values (50304, '%1: Cannot delete row [%2] for unknown reason.', 16, 'Setup Script', getdate(), 'Setup Script', getdate())
Insert dbo.ErrorMessages (ErrorMessageID, ErrorDescription, Severity, CreatedBy, CreatedDate, LastModifiedBy, LastModifiedDate)
values (50305, '%1: Cannot insert row for unknown reason.', 16, 'Setup Script', getdate(), 'Setup Script', getdate())
Insert dbo.ErrorMessages (ErrorMessageID, ErrorDescription, Severity, CreatedBy, CreatedDate, LastModifiedBy, LastModifiedDate)
values (50306, '%1: Unable to display rows for unknown reason.', 16, 'Setup Script', getdate(), 'Setup Script', getdate())
Insert dbo.ErrorMessages (ErrorMessageID, ErrorDescription, Severity, CreatedBy, CreatedDate, LastModifiedBy, LastModifiedDate)
values (50307, '%1 already exists. This has to be unique.', 16, 'Setup Script', getdate(), 'Setup Script', getdate())
Insert dbo.ErrorMessages (ErrorMessageID, ErrorDescription, Severity, CreatedBy, CreatedDate, LastModifiedBy, LastModifiedDate)
values (50308, 'User name or password do not match.', 16, 'Setup Script', getdate(), 'Setup Script', getdate())
Insert dbo.ErrorMessages (ErrorMessageID, ErrorDescription, Severity, CreatedBy, CreatedDate, LastModifiedBy, LastModifiedDate)
values (50309, 'Old and new password should not be the same.', 16, 'Setup Script', getdate(), 'Setup Script', getdate())
Insert dbo.ErrorMessages (ErrorMessageID, ErrorDescription, Severity, CreatedBy, CreatedDate, LastModifiedBy, LastModifiedDate)
values (50310, 'Cannot change password. Old password do not match.', 16, 'Setup Script', getdate(), 'Setup Script', getdate())
Insert dbo.ErrorMessages (ErrorMessageID, ErrorDescription, Severity, CreatedBy, CreatedDate, LastModifiedBy, LastModifiedDate)
values (50311, 'You do not have access to complete this task.', 16, 'Setup Script', getdate(), 'Setup Script', getdate())
Insert dbo.ErrorMessages (ErrorMessageID, ErrorDescription, Severity, CreatedBy, CreatedDate, LastModifiedBy, LastModifiedDate)
values (50313, 'Email address is alread in use. Try diffrent email address.', 16, 'Setup Script', getdate(), 'Setup Script', getdate())
Insert dbo.ErrorMessages (ErrorMessageID, ErrorDescription, Severity, CreatedBy, CreatedDate, LastModifiedBy, LastModifiedDate)
values (50314, 'Invalid operation requested.', 16, 'Setup Script', getdate(), 'Setup Script', getdate())
Insert dbo.ErrorMessages (ErrorMessageID, ErrorDescription, Severity, CreatedBy, CreatedDate, LastModifiedBy, LastModifiedDate)
values (50315, '%1 is in use. You cannot delete this record.', 16, 'Setup Script', getdate(), 'Setup Script', getdate())
Insert dbo.ErrorMessages (ErrorMessageID, ErrorDescription, Severity, CreatedBy, CreatedDate, LastModifiedBy, LastModifiedDate)
values (50320, 'You are not allowed to change the role assigment of yourself.', 16, 'Setup Script', getdate(), 'Setup Script', getdate())
Insert dbo.ErrorMessages (ErrorMessageID, ErrorDescription, Severity, CreatedBy, CreatedDate, LastModifiedBy, LastModifiedDate)
values (50321, 'You are not allowed to delete your own account.', 16, 'Setup Script', getdate(), 'Setup Script', getdate())
Insert dbo.ErrorMessages (ErrorMessageID, ErrorDescription, Severity, CreatedBy, CreatedDate, LastModifiedBy, LastModifiedDate)
values (50322, 'Cannot delete the record as %1 is expired.', 16, 'Setup Script', getdate(), 'Setup Script', getdate())
go

